# Probe Viz

In [30]:
import torch
import torch.nn.functional as F
import json

import matplotlib.pyplot as plt

import sys      
sys.path.insert(0, "/storage/project/r-aivanova7-0/shared/eyas/geometry_of_truth_replication")
from src.activations import load_acts
from src.probes import load_probe_results
from src.pca import load_pca_results

In [34]:
MODEL = "llama-3.1-8b"
LAYER = 15
DATASET_NAME = "cities"
ACTS_DIR     = "/storage/home/hcoda1/7/eayesh3/scratch/geometry_of_truth/acts"
PCA_DIR     = f"/storage/home/hcoda1/7/eayesh3/scratch/geometry_of_truth/pca/{MODEL}"
PROBES_DIR = f"/storage/home/hcoda1/7/eayesh3/scratch/geometry_of_truth/probes/{MODEL}/layer_{LAYER}"
DATASET_CSV = f"../datasets/{DATASET_NAME}.csv"

In [27]:
df = load_probe_results(f"{PROBES_DIR}/results.json")
df.loc[('cities')]

                             lr      mm  mm_cov     n
test_dataset
cities                   0.9967  0.9833  0.9933   299
neg_cities               0.6384  0.8021  0.1384  1496
sp_en_trans              0.9379  1.0000  0.8616   354
neg_sp_en_trans          0.3701  0.2401  0.0876   354
larger_than              0.5419  0.9091  0.6212  1980
smaller_than             0.6626  0.8914  0.7803  1980
cities_cities_conj       0.9059  0.8618  0.3818  1498
cities_cities_disj       0.6595  0.8531  0.7530  1498
companies_true_false     0.5608  0.5675  0.5758  1200
common_claim_true_false  0.7534  0.7593  0.5874  2048
counterfact_true_false   0.7314  0.6631  0.6528  2048
likely                   0.6323  0.6553  0.5122  2048

In [28]:
df.loc[('cities+neg_cities')]

                             lr      mm  mm_cov     n
test_dataset
cities                   0.9980  0.9559  0.9993  1496
neg_cities               0.9987  0.9993  1.0000  1496
sp_en_trans              0.9915  0.9633  0.7655   354
neg_sp_en_trans          0.9605  0.9915  0.5537   354
larger_than              0.7485  0.9232  0.5111  1980
smaller_than             0.8268  0.9157  0.8460  1980
cities_cities_conj       0.8999  0.8758  0.5347  1498
cities_cities_disj       0.7250  0.7984  0.6816  1498
companies_true_false     0.5767  0.6300  0.5475  1200
common_claim_true_false  0.7593  0.7412  0.5210  2048
counterfact_true_false   0.7104  0.6206  0.5444  2048
likely                   0.6348  0.6475  0.5151  2048

In [29]:
df.loc[('cities+neg_cities')]-df.loc[('cities')]

                             lr      mm  mm_cov     n
test_dataset
cities                   0.0013 -0.0274  0.0060  1197
neg_cities               0.3603  0.1972  0.8616     0
sp_en_trans              0.0536 -0.0367 -0.0961     0
neg_sp_en_trans          0.5904  0.7514  0.4661     0
larger_than              0.2066  0.0141 -0.1101     0
smaller_than             0.1642  0.0243  0.0657     0
cities_cities_conj      -0.0060  0.0140  0.1529     0
cities_cities_disj       0.0655 -0.0547 -0.0714     0
companies_true_false     0.0159  0.0625 -0.0283     0
common_claim_true_false  0.0059 -0.0181 -0.0664     0
counterfact_true_false  -0.0210 -0.0425 -0.1084     0
likely                   0.0025 -0.0078  0.0029     0

In [37]:
path_to_pcaResult = f"{PCA_DIR}/cities/pca_layer{LAYER}.pt"
cities_PCA = load_pca_results(path_to_pcaResult)

In [39]:
neg_cities_acts = load_acts(MODEL,"neg_cities",LAYER,ACTS_DIR,False)